[package]
name = "revset"
version = "0.0.1"
authors = ["Facebook"]
license = "GPLv2+"
edition = "2018"

[dependencies]
error-chain = "0.11.0"
futures = "0.1.17"
maplit = "1.0.0"
thiserror = "1.0.5"

asyncmemo = { path = "../asyncmemo" }
mercurial_types = { path = "../mercurial_types" }
repoinfo = { path = "../repoinfo" }
