[package]
name = "bookmarks"
version = "0.0.1"
authors = ["Facebook"]
license = "GPLv2+"
edition = "2018"

[dependencies]
ascii = "0.8.6"
futures = "0.1.17"
serde_derive = "1.0.66"
serde = "1.0.66"

futures_ext = { path = "../futures_ext" }
storage-types = { path = "../storage/types" }
