[package]
name = "bundle2_resolver"
version = "0.0.1"
authors = ["Facebook"]
license = "GPLv2+"
edition = "2018"

[dependencies]
ascii = "0.8.6"
bytes = "0.4.5"
futures = "0.1.17"

futures-ext = { path = "../futures-ext" }
