# @autocargo from //scm/mononoke/mononoke_types:mononoke_types-thrift
# Signature<<7b5503bfb2a148d873281f9aa2739467b29c7815>>
[package]
name = "mononoke_types-thrift"
edition = "2018"
version = "0.0.0"
include = ["thrift_lib.rs"]
build = "thrift_build.rs"

[lib]
path = "thrift_lib.rs"

[build-dependencies]
build_script_helpers = { path = "../../../../common/rust/cargo_from_buck/build_script_helpers" }

[dependencies]
buck_gen_proc_macro = { path = "../../../../common/rust/cargo_from_buck/buck_gen_proc_macro" }
fbthrift = { path = "../../../../thrift/lib/rust" }
anyhow = "*"
async-trait = { version = "*", features = ["support_old_nightly"] }
futures = "0.1"
futures-preview = { package = "futures-preview", version = "=0.3.0-alpha.19", features = ["async-await", "compat"] } # prerelease using standard library futures
lazy_static = "*"
serde = "*"
serde_derive = "*"
thiserror = "*"
# @end of Signature<<7b5503bfb2a148d873281f9aa2739467b29c7815>>
