[package]
name = "bookmarks"
version = "0.0.1"
authors = ["Facebook"]
license = "GPLv2+"

[dependencies]
futures = "0.1.17"
serde_derive = "1.0.20"
serde = "1.0.20"

futures-ext = { path = "../futures-ext" }
storage-types = { path = "../storage/types" }
