[package]
name = "metaconfig"
version = "0.0.1"
authors = ["Facebook"]
license = "GPLv2+"
edition = "2018"

[dependencies]
error-chain = "0.11.0"
futures = "0.1.17"
thiserror = "1.0.5"

mercurial = { path = "../mercurial" }
