[package]
name = "blobrepo"
version = "0.0.1"
authors = ["Facebook"]
license = "GPLv2+"
edition = "2018"

[dependencies]
bincode = "1.0.0"
bytes = "0.4.8"
error-chain = "0.11.0"
futures = "0.1.17"
heapsize = "0.4.2"
heapsize_derive = "0.1.4"
serde = "1.0.66"
serde_derive = "1.0.66"
thiserror = "1.0.5"
tokio-core = "0.1.17"
